"""empty message

Revision ID: 3459fc77134a
Revises: 8eeb196fc682
Create Date: 2022-12-22 17:38:35.506985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3459fc77134a'
down_revision = '8eeb196fc682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.alter_column('min_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=25, scale=8),
               existing_comment='最少可借额度',
               existing_nullable=False)
        batch_op.alter_column('rate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_comment='利率',
               existing_nullable=False)
        batch_op.alter_column('over_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_comment='逾期利率',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.alter_column('over_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_comment='逾期利率',
               existing_nullable=False)
        batch_op.alter_column('rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_comment='利率',
               existing_nullable=False)
        batch_op.alter_column('min_amount',
               existing_type=sa.DECIMAL(precision=25, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_comment='最少可借额度',
               existing_nullable=False)

    # ### end Alembic commands ###
