"""empty message

Revision ID: 3ea3a62fa7fc
Revises: 561c2f478eea
Create Date: 2022-12-22 16:37:47.580862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ea3a62fa7fc'
down_revision = '561c2f478eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='性别')
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='年龄')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='年龄')
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='性别')

    # ### end Alembic commands ###
