"""empty message

Revision ID: 70b2031d3a39
Revises: 3ea3a62fa7fc
Create Date: 2022-12-22 17:34:58.888557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b2031d3a39'
down_revision = '3ea3a62fa7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_currency',
    sa.Column('createTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updateTime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('currency', sa.String(length=32), nullable=False, comment='货币'),
    sa.Column('max_amount', sa.String(length=20), nullable=False, comment='最多可借额度'),
    sa.Column('min_amount', sa.String(length=20), nullable=False, comment='最少可借额度'),
    sa.Column('rate', sa.String(length=10), nullable=False, comment='利率'),
    sa.Column('over_rate', sa.String(length=10), nullable=False, comment='逾期利率'),
    sa.Column('isActive', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debit_currency_currency'), ['currency'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_currency_currency'))

    op.drop_table('debit_currency')
    # ### end Alembic commands ###
