"""empty message

Revision ID: 7d14e3add644
Revises: ccf1d2ddccda
Create Date: 2022-12-23 00:13:39.965133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d14e3add644'
down_revision = 'ccf1d2ddccda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=False, comment='借款天数'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.drop_column('days')

    # ### end Alembic commands ###
