"""empty message

Revision ID: 8eeb196fc682
Revises: 65a7fe156452
Create Date: 2022-12-22 17:37:48.847824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8eeb196fc682'
down_revision = '65a7fe156452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.alter_column('max_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=25, scale=8),
               existing_comment='最多可借额度',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.alter_column('max_amount',
               existing_type=sa.DECIMAL(precision=25, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_comment='最多可借额度',
               existing_nullable=False)

    # ### end Alembic commands ###
