"""empty message

Revision ID: a7ab75833848
Revises: 7d14e3add644
Create Date: 2022-12-23 01:32:11.667600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ab75833848'
down_revision = '7d14e3add644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repaymentTime', sa.Date(), nullable=True, comment='还款时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.drop_column('repaymentTime')

    # ### end Alembic commands ###
