"""empty message

Revision ID: ccf1d2ddccda
Revises: f87ea90d5ed0
Create Date: 2022-12-22 23:55:24.372738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf1d2ddccda'
down_revision = 'f87ea90d5ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_order',
    sa.Column('createTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updateTime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='金额'),
    sa.Column('fee', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='手续费'),
    sa.Column('liquidated_damages', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='违约金'),
    sa.Column('prepayment_interest', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='提前还款利息'),
    sa.Column('rate', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='利率'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 1进行中 2完成'),
    sa.Column('startTime', sa.Date(), nullable=True, comment='开始时间'),
    sa.Column('endTime', sa.Date(), nullable=True, comment='结束时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('currency_id', sa.Integer(), nullable=False, comment='币种ID'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debit_order_currency_id'), ['currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_order_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_debit_order_currency_id'))

    op.drop_table('debit_order')
    # ### end Alembic commands ###
