"""empty message

Revision ID: f36227b1e639
Revises: 3459fc77134a
Create Date: 2022-12-22 18:23:10.828108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f36227b1e639'
down_revision = '3459fc77134a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('createTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updateTime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('currency_name', sa.String(length=32), nullable=False, comment='货币名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='货币图标'),
    sa.Column('isActive', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_currency_name'), ['currency_name'], unique=False)

    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue_rate', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='逾期利率'))
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=False, comment='货币ID'))
        batch_op.drop_index('ix_debit_currency_currency')
        batch_op.create_foreign_key(None, 'currency', ['currency_id'], ['id'])
        batch_op.drop_column('currency')
        batch_op.drop_column('over_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('over_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False, comment='逾期利率'))
        batch_op.add_column(sa.Column('currency', mysql.VARCHAR(length=32), nullable=False, comment='货币'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_debit_currency_currency', ['currency'], unique=False)
        batch_op.drop_column('currency_id')
        batch_op.drop_column('overdue_rate')

    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_currency_name'))

    op.drop_table('currency')
    # ### end Alembic commands ###
